module.exports = {
  apps: [
    {
      name: "tuneforge-miner-1",
      script: "/home/borgg/tuneforge/venv/bin/python3",
      args: "-m neurons.miner --env-file .env.miner",
      cwd: __dirname,
      interpreter: "none",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env: {
        PYTHONUNBUFFERED: "1",
      },
    },
    {
      name: "tuneforge-miner-2",
      script: "/home/borgg/tuneforge/venv/bin/python3",
      args: "-m neurons.miner --env-file .env.miner2",
      cwd: __dirname,
      interpreter: "none",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env: {
        PYTHONUNBUFFERED: "1",
      },
    },
    {
      name: "tuneforge-validator",
      script: "/home/borgg/tuneforge/venv/bin/python3",
      args: "-m neurons.validator --env-file .env.validator",
      cwd: __dirname,
      interpreter: "none",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env: {
        PYTHONUNBUFFERED: "1",
        CUDA_VISIBLE_DEVICES: "-1",
      },
    },
    {
      name: "tuneforge-api",
      script: "/home/borgg/tuneforge/venv/bin/python3",
      args: "-m uvicorn tuneforge.api.server:app --host 0.0.0.0 --port 8000",
      cwd: __dirname,
      interpreter: "none",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        PYTHONUNBUFFERED: "1",
        TF_NETUID: "234",
        TF_SUBTENSOR_NETWORK: "test",
        TF_WALLET_NAME: "test-coldkey",
        TF_WALLET_HOTKEY: "hotkey-validator",
        TF_MODE: "validator",
        TF_DB_URL: "postgresql+asyncpg://tuneforge:tuneforge_dev@localhost:5432/tuneforge",
        TF_STORAGE_BACKEND: "postgres",
        TF_VALIDATOR_SERVICE_TOKEN: "h5b2XVetVi75ALHV_jZzGbyz5ew_GVv4Y1T-K8VvcCI",
        TF_JWT_SECRET: "dev-secret-change-me",
      },
    },
    {
      name: "tuneforge-web",
      script: "npm",
      args: "run dev",
      cwd: "/home/borgg/tuneforge-web",
      interpreter: "none",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NEXT_PUBLIC_API_URL: "http://192.168.1.83:8000",
      },
    },
  ],
};
