"""
TuneForge database package.

Re-exports the core Database class, ORM models, CRUD operations,
and helper functions for use throughout the API.
"""

from tuneforge.api.database.engine import Database, total_pages
from tuneforge.api.database.models import (
    AnnotationMilestoneRow,
    AnnotationRow,
    AnnotationStreakRow,
    AnnotationTaskRow,
    AnnotatorReliabilityRow,
    ApiKeyRow,
    AudioBlobRow,
    Base,
    CreditRow,
    CreditTransactionRow,
    GenerationRow,
    PreferenceModelRow,
    TrackRow,
    UserRow,
    ValidationAudioRow,
    ValidationRoundRow,
    row_to_scores,
)
from tuneforge.api.database.crud import (
    create_annotation_tasks_from_round,
    create_api_key,
    create_audio_blob,
    create_credit,
    create_credit_transaction,
    create_generation,
    create_gold_task,
    create_preference_model,
    create_track,
    create_user,
    create_validation_audio,
    create_validation_round,
    delete_audio_blob,
    delete_gold_task,
    delete_track,
    export_resolved_annotations,
    flag_annotator,
    get_active_preference_model,
    get_all_annotator_reliabilities,
    get_annotation_stats,
    get_annotation_task,
    get_annotation_tasks,
    get_annotator_reliability,
    get_api_key_by_hash,
    get_audio_blob,
    get_credit,
    get_credit_transactions,
    get_generation,
    get_gold_tasks,
    get_next_annotation_task,
    get_track,
    get_track_count,
    get_tracks_by_generation,
    get_user_annotation_progress,
    get_user_api_keys,
    get_user_by_email,
    get_user_by_google_id,
    get_user_by_id,
    get_validation_audio_by_round,
    get_validation_rounds,
    revoke_api_key,
    search_tracks,
    submit_annotation,
    unflag_annotator,
    update_api_key_last_used,
    update_generation_status,
    update_user,
    update_validation_audio_scores,
    # Milestones
    check_and_claim_milestones,
    claim_milestone,
    get_claimed_milestone_keys,
    get_claimed_milestones,
    get_user_trusted_annotation_count,
    # Streaks & recurring rewards
    check_and_claim_recurring_reward,
    get_or_create_streak,
    get_streak_info,
    get_user_daily_trusted_annotation_count,
    update_streak,
)

__all__ = [
    # Engine
    "Database",
    "total_pages",
    # Base
    "Base",
    # Models
    "AnnotationRow",
    "AnnotationTaskRow",
    "ApiKeyRow",
    "AudioBlobRow",
    "CreditRow",
    "CreditTransactionRow",
    "GenerationRow",
    "PreferenceModelRow",
    "TrackRow",
    "UserRow",
    "ValidationAudioRow",
    "ValidationRoundRow",
    # Helpers
    "row_to_scores",
    # CRUD - Tracks
    "create_track",
    "delete_track",
    "get_track",
    "search_tracks",
    "get_track_count",
    "get_tracks_by_generation",
    # CRUD - Audio blobs
    "create_audio_blob",
    "get_audio_blob",
    "delete_audio_blob",
    # CRUD - Validation rounds
    "create_validation_round",
    "create_validation_audio",
    "get_validation_rounds",
    "get_validation_audio_by_round",
    "update_validation_audio_scores",
    # CRUD - Annotations
    "create_annotation_tasks_from_round",
    "get_next_annotation_task",
    "submit_annotation",
    "get_annotation_task",
    "get_annotation_tasks",
    "get_annotation_stats",
    "get_user_annotation_progress",
    "export_resolved_annotations",
    # CRUD - Gold standard QC
    "create_gold_task",
    "get_gold_tasks",
    "delete_gold_task",
    "get_annotator_reliability",
    "get_all_annotator_reliabilities",
    "flag_annotator",
    "unflag_annotator",
    # Models
    "AnnotationMilestoneRow",
    "AnnotatorReliabilityRow",
    # CRUD - Preference models
    "create_preference_model",
    "get_active_preference_model",
    # CRUD - Users
    "create_user",
    "get_user_by_email",
    "get_user_by_id",
    "get_user_by_google_id",
    "update_user",
    # CRUD - Credits
    "create_credit",
    "get_credit",
    "create_credit_transaction",
    "get_credit_transactions",
    # CRUD - Generations
    "create_generation",
    "get_generation",
    "update_generation_status",
    # CRUD - API Keys
    "create_api_key",
    "get_api_key_by_hash",
    "get_user_api_keys",
    "revoke_api_key",
    "update_api_key_last_used",
    # CRUD - Milestones
    "check_and_claim_milestones",
    "claim_milestone",
    "get_claimed_milestone_keys",
    "get_claimed_milestones",
    "get_user_trusted_annotation_count",
    # Models - Streaks
    "AnnotationStreakRow",
    # CRUD - Streaks & recurring rewards
    "check_and_claim_recurring_reward",
    "get_or_create_streak",
    "get_streak_info",
    "get_user_daily_trusted_annotation_count",
    "update_streak",
]
